import { ItemSchema, itemCacheKey, items, type Item } from '@app/shared';
import { eq } from 'drizzle-orm';
import type { Cache } from '../cache.js';
import { config } from '../config.js';
import type { Db } from '../db.js';
import { logger } from '../logger.js';

/**
 * Items repository: Postgres is the system of record, Valkey the cache in
 * front of it (cache-aside). The hydrator bulk write-throughs both stores on
 * its schedule; the api reads the cache first, falls back to Postgres, and
 * re-populates the key with a fresh TTL so the next reads hit the cache
 * again. A cache problem (down, garbage value, missing key) is always a miss,
 * never an error — and a failed write-back never fails the request.
 */

export async function listItems(db: Db): Promise<Item[]> {
  return db.select().from(items).orderBy(items.id);
}

export async function getItem(db: Db, cache: Cache, id: number): Promise<Item | undefined> {
  try {
    const hit = await cache.get(itemCacheKey(id));
    if (hit !== null) {
      const parsed = ItemSchema.safeParse(JSON.parse(hit));
      if (parsed.success) return parsed.data;
      logger.warn({ id }, 'Cache value failed validation, falling back to Postgres');
    }
  } catch (err) {
    logger.warn({ err, id }, 'Cache read failed, falling back to Postgres');
  }

  const rows = await db.select().from(items).where(eq(items.id, id)).limit(1);
  const item = rows[0];

  // Cache-aside write-back: repopulate the missing/expired key. Best-effort.
  if (item) {
    try {
      await cache.set(itemCacheKey(id), JSON.stringify(item), 'EX', config.cache.ttlSeconds);
    } catch (err) {
      logger.warn({ err, id }, 'Cache write-back failed');
    }
  }
  return item;
}

export async function createItem(db: Db, name: string): Promise<Item> {
  // The id is generated by the identity column. The new row reaches the cache
  // on the next hydration run; until then getItem falls back to Postgres.
  const rows = await db.insert(items).values({ name }).returning();
  const row = rows[0];
  if (!row) throw new Error('Insert returned no row');
  return row;
}
